site_name: Nexus Git Documentation
site_url: https://thenexusavenger.github.io/Nexus-Git
repo_name: TheNexusAvenger/Nexus-Git
repo_url: https://github.com/TheNexusAvenger/Nexus-Git

theme:
  name: 'material'
  palette:
    primary: 'Blue'
    accent: 'Light Blue'

nav:
  - Home: index.md
  - Getting Started:
    - Overview: getting-started/overview.md
    - Setup: getting-started/setup.md
  - Building: building.md
  - Contributing: contributing.md

markdown_extensions:
  - admonition
  - codehilite